apiVersion: v1
kind: Service
metadata:
  name: guestbook-backend
  namespace: sample-guestbook
  annotations:
spec:
  selector:
    app: guestbook
  ports:
    - port: 80         
      targetPort: 3000 
      protocol: TCP
  type: ClusterIP